---

- name: Update apt repositories cache
  apt:
    update_cache: yes

- name: Install updates of all currently installed packages
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

- name: Install common packages
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
  vars:
    packages:
      - ufw
      - htop
      - nano
      - sudo
      - git
